# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('hash', models.CharField(max_length=200, unique=True)),
                ('expiration', models.DateTimeField()),
                ('expired', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledOutage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('hash', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='landingpagechoice',
            name='hide_from_users',
            field=models.BooleanField(default=False, help_text='Hides this choice from normal users. When checked, only staff, technicians, and super-users can see the choice'),
        ),
        migrations.AlterField(
            model_name='interlock',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (1, 'Unlocked'), (0, 'Locked')], default=-1),
        ),
        migrations.AlterField(
            model_name='physicalaccesslevel',
            name='schedule',
            field=models.IntegerField(choices=[(0, 'Always'), (1, 'Weekdays, 9am to 5pm'), (2, 'Weekends')]),
        ),
    ]
