# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0004_auto_20181018_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='reservation_required',
            field=models.BooleanField(default=False, help_text='Require that users have a current (within 15 minutes) reservation in order to use the tool'),
        ),
    ]
