# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0005_tool_reservation_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='manager_email',
            field=models.EmailField(blank=True, help_text='Email address of the account manager', max_length=254, null=True),
        ),
    ]
