# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0006_account_manager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='shutdown',
            field=models.BooleanField(default=False, help_text='Whether or not tool was shut down during this period'),
        ),
    ]
