# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0008_auto_20181226_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usertype',
            name='staff_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
