# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0010_chemicalrequest_userchemical'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchemical',
            name='sds_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
