# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-14 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0012_auto_20190218_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentor_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.TextField(blank=True, help_text='for internal staff use'),
        ),
        migrations.AlterField(
            model_name='landingpagechoice',
            name='notifications',
            field=models.CharField(blank=True, choices=[('news', 'News creation and updates - notifies all users'), ('safetyissue', 'New safety issues - notifies staff only')], help_text="Displays the number of new notifications for the user. For example, if the user has two unread news notifications then the number '2' would appear for the news icon on the landing page.", max_length=25, null=True),
        ),
    ]
