# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-14 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0013_auto_20200114_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name'], 'permissions': (('trigger_timed_services', 'Can trigger timed services'), ('use_billing_api', 'Can use billing API'), ('kiosk', 'Kiosk services'))},
        ),
    ]
