# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0015_auto_20200115_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fire_trained',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mentor_trained',
            field=models.DateField(blank=True, null=True),
        ),
    ]
