# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0016_auto_20200115_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='post address / contact information'),
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.DeleteModel(
            name='ContactInformationCategory',
        ),
    ]
