# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0017_auto_20200115_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='phone number'),
        ),
    ]
