# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0021_auto_20200117_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoutage',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.Resource'),
        ),
    ]
