# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-20 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0024_auto_20200204_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='external_link',
            field=models.CharField(blank=True, help_text='Weblink to external resource (equipment page etc)', max_length=200, null=True),
        ),
    ]
