# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-06 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0025_tool_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='usage_link',
            field=models.CharField(blank=True, help_text='Weblink to external usage logging', max_length=200, null=True),
        ),
    ]
