# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-28 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0027_auto_20200426_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
