# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0028_auto_20200429_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit by the user (e.g for badge), to be returned when leaving.', max_digits=6),
        ),
    ]
