# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0029_user_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='E-mail address of administrative contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='admin_name',
            field=models.CharField(blank=True, help_text='Contact person for administration, unless already covered by technical contact', max_length=100, null=True),
        ),
    ]
