# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-08 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0030_auto_20200603_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equiresp_trained',
            field=models.DateField(blank=True, null=True),
        ),
    ]
