# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0032_tool_reservation_physical_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Allow for unlimited parallel reservation and use.'),
        ),
    ]
