# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0033_tool_virtual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='virtual',
        ),
        migrations.AddField(
            model_name='tool',
            name='multiplicity',
            field=models.PositiveIntegerField(default=1, help_text='Number of parallel user slots, normally 1 (0=virtual/infinite).'),
        ),
    ]
