# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0034_auto_20200713_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personnel_number',
            field=models.PositiveIntegerField(blank=True, help_text='The personnel number associated with this user.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_number',
            field=models.PositiveIntegerField(blank=True, help_text='The badge number associated with this user.', null=True, unique=True),
        ),
    ]
