# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0036_tool_billing_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='billing_reference',
            field=models.CharField(blank=True, help_text='tool reference used by financial backend', max_length=20, null=True),
        ),
    ]
