# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0038_tool_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billing_reference',
            field=models.CharField(blank=True, help_text='project reference used by financial backend', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='private',
            field=models.BooleanField(default=False, help_text='Marking the tool private will restrict visibility to staff.'),
        ),
    ]
