# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0039_auto_20201117_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='usage_warning',
            field=models.CharField(blank=True, help_text='Warning displayed next to start/stop usage button', max_length=200, null=True),
        ),
    ]
