# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0041_auto_20201124_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='title',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
