# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0042_usageevent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='title',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
