FROM python:3.6

COPY . /nemodemo/

RUN pip install /nemodemo/
RUN rm --recursive --force /nemodemo

RUN mkdir /nemodemo
RUN mkdir /nemodemo/media
WORKDIR /nemodemo

COPY resources/icons/* /nemodemo/media/
COPY resources/people/* /nemodemo/media/
COPY resources/splash_pad_settings.py /nemodemo/
COPY NEMO/fixtures/splash_pad.json /nemodemo/

ENV DJANGO_SETTINGS_MODULE "splash_pad_settings"
ENV PYTHONPATH "/nemodemo/"

RUN django-admin makemigrations NEMO
RUN django-admin migrate
RUN django-admin loaddata splash_pad.json

ENV REMOTE_USER "captain"
EXPOSE 8000/tcp
CMD ["django-admin","runserver","0.0.0.0:8000"]
